homebridge/HAP-NodeJS

index.js, package.json
With this commit the HAP-NodeJS can be used as a module to other (bridge) implementations. The object factories are exposed in the index.js. package.json defines current dependencies.
=> add npm package.json and index.js to publish relevant object factories

AccessoryController.js, Characteristic.js, Server.js, accessories/GarageDoorOpener_accessory.js
This makes the characteristic reads callback based. This way we can have our `onRead` functions be async. We're fetching state here, so its useful to be able to use callbacks.
Here's an example in use:
```js
onRead: function(callback) {
this.getBrightness(function(level){
callback(level);
});
}
```
Ok, I barely know what I'm doing, but I basically just went up the stack making sure everything supported using a callback. The only place I got in trouble was in `Server.js` where the `JSON` is written to the response. The callback style works fine, the only problem is, on the first call through this stack, the `onRead` hasn't been defined yet. So everything just goes to 💩 and hangs. 
I'm not sure if this is actually a bug or what. I just handled it by sending back an empty string of `JSON`, …
=> Async Characteristic Reads

AccessoryController.js, BridgedAccessoryController.js, BridgedCore.js, Characteristic.js, Core.js, Server.js, accessories/GarageDoorOpener_accessory.js
:construction: :construction:  Don't merge yet. Needs discussion :construction: :construction: 
Ok, this is try number 2 to get async state checks for accessories. These are fresh commits since the last ones were actually merged, but then reverted.
This adds callbacks to the `onRead` function, so that we can have asynchronous calls to fetch the state of accessories. HAP-NodeJS might not be the only pace that accessories/devices will be controlled from. So this means HAP-NodeJS won't always have the actual current state. 
Because of this, we need to somehow fetch the current state of an accessory. To do this, we'll need to use callbacks to return the values when we've fetched them. That's what this pull enables.
[According to some …
=> Async onRead

BridgedCore.js, accessories/Lock_accessory.js, lib/Accessory.js, lib/HAPServer.js
- Restore ability to identify unpaired Accessories during browsing
- Simplify Accessory identification with new unified 'identify' event
- Example usage in `Lock_accessory.js`
=> Improved Accessory identification

lib/Characteristic.js, lib/HAPServer.js, lib/util/once.js
Especially for Characteristic get/set events, we want to make sure that
calling them twice results in an Error (as this will otherwise cause
unpredictable problems).
=> Protect certain callbacks against multiple calls

lib/Accessory.js, lib/HAPServer.js
- Move the "get characteristics loop" to Accessory, matching "set
characteristics" design
- Handles properly when get-accessory calls back with an error
=> Handle errors cleanly in get-characteristics

lib/Service.js
Replacement for  #128, tailored for @KhaosT 's wishes, as voiced in https://github.com/KhaosT/HAP-NodeJS/issues/121#issuecomment-139820333
>@snowdd1 Sorry for the confusion, I think having the ability to return a new optional characteristic on get characteristic is the one I want to keep. 
`Service.getCharacteristic(name)` now returns a new Characteristic object if the Characteristic is not yet present, but the name passed is an instance of an optional Characteristic of that service, like `Characteristic.Brightness` for a `Service.Lightbulb`.
To keep a possibility to test for the existence of a Characteristic *without* accidentally adding it I introduced a new separate function `Service.testCharacteristic(name)` which returns a Boolean value.
This PR does not introduce any slightly …
=> Lightweight get-characteristic change

lib/Service.js
You are looping through the "optionalCharacteristics", but trying to read at the index of the normal "characteristics". Therefore it will always return "undefined" when you request optional characteristics via "getCharateristics".
=> Updated Service.js

lib/Accessory.js, lib/HAPServer.js
- Fix bug where call to `/characteristics` could result in multiple
HTTP responses
- Use 207 multi-status for get/set
- Fix bug where incorrect error response was returned for get+set
characteristics (resulting in client disconnect)
=> Fixes for characteristic get/set

lib/model/AccessoryInfo.js, lib/model/IdentifierCache.js
persistSync() should not be called, before seItem() is ready. In my case, AccessoryInfo files were cleared, which caused recreation and ultimately preventing reconnection. Calling synchronous setItemSync() fixes that.
=> Prevent clearing AccessoryInfo files

lib/Characteristic.js
otherwise iOS complains and about half of the accessories won't appear
=> added maxLen validation for string characteristics

package.json
'npm install' warns about no license field available in package.json.
=> Change deprecated 'licenses' property to 'license'

lib/util/eventedhttp.js
This version actually tries a different port if the OS-generated port is in use...
=> EventedHTTPServer: Don’t assume high-numbered ports aren’t in use (#131).

lib/Accessory.js
Okay if there’s a reason not to do this, just seemed like it would be handy. I’m going to iterate `services` in client code to do the same thing. I suppose this could potentially be a breaking change, even with it as the last `||`, but probably very unlikely that it would break anything.
=> Allow to getService by subtype string

README.md
The link to Apple's DMCA was broken. Presumably GitHub updated the folder structure in their DMCA repo. This PR fixes the link in the readme.
=> Fix Apple DMCA link

accessories/Fan_accessory.js
When setting the fan speed for a "fake" fan, this fix ensures that we remember the fan speed so that Apple Home shows it correctly.
=> Fixed the fan speed

package.json
curve25519-n isn't building on Windows 10. curve25519-n2 includes code to handle building on Windows 10. There are no other changes.
=> change curve25519-n to curve25519-n2 to support Windows

accessories/AirConditioner_accessory.js, lib/Accessory.js, lib/Characteristic.js, lib/Service.js, lib/gen/HomeKitTypes-Bridge.js, lib/gen/HomeKitTypes.js, package.json
There are many changes in the HomeKit Accessory Simulator metadata. Please review this list and let me know if anything needs to be manually put back:
Camera Related Items:
Characteristic.SelectedStreamConfiguration renamed to Characteristic.SelectedRTPStreamConfiguration
Service.CameraControl Removed
Characteristic.DigitalZoom no longer attached to any service
Characteristic.ImageMirroring no longer attached to any service
Characteristic.ImageRotation no longer attached to any service
Characteristic.NightVision no longer attached to any service
Characteristic.OpticalZoom no longer attached to any service
Characteristic.StreamingStatus is now writable
Utility Items:
Service.Label renamed to Service.ServiceLabel
Characteristic.LabelNamespace renamed to Characteristic.ServiceLabelNamespace …
=> Updates for IOS 11 / XCode 9

lib/Accessory.js, lib/Service.js, package.json
This is intended to fix nfarina/homebridge#1433
The issue is that Apple removed an optional characteristic and so now, while the characteristic still exists, it's no longer in the optional list. This change would allow "getCharacteristic" to still auto-add it while displaying a warning so that the developer understands that the characteristic isn't in the optional list. If the developer uses "addCharacteristic" then the warning will not appear.
Is this a good way to handle this or should we just make the developer of that plugin fix the plugin to add?
I don't want to add the defunct characteristic as optional on the service because I want to make sure future projects don't see it as an option.
=> Allow any characteristic to auto-add to a service when getting it.

lib/Accessory.js
If a bridge is published without any accessories and the accessories are added later the functionality to expire unused ids in the IdentifierCache is removing all the ID's and that's creating mess on the iOS later when the accessories are dynamically added. So i added functionality to disable the 'expire unusdes ids' also a check in the publish weather the accessory is bridge and the length of bridgedAccessories in the bridge is 0 then disable the 'expire unusdes ids'.
=> expire unused ids optional

lib/Accessory.js, lib/Characteristic.js, lib/HAPServer.js, lib/util/eventedhttp.js
This pull request provides characteristics with subscription status knowledge. This is helpful to interact with external devices that are battery operated, but do provide on demand notifications of status changes. Especially helpful to implement the Bluetooth range extender. See #540.
=> Provide subscription status to characteristics

lib/gen/HomeKitTypes.js
The new services for faucets, irrigation, and shower systems have finally been added. But they are missing `minValue`, `maxValue` and `validValues`. 
This PR adds them so that the new services are more in line with the others.
=> Improve the new services with minValue, maxValue and validValues

index.js, lib/Accessory.js, lib/Characteristic.js
I have been moving my plugins away from using getValue to return the current accessory state, and switching to a event based model, and having the plugin push state via updateValue or setValue. ( I'm switching to this event based model, to improve the responsiveness of the Home app and reduce the lagging caused by the callouts to remote devices to return state. ) While this works really well, what is lacking is the ability to deal with accessories that are not responding for various reasons, as the updateValue and setValue don't accept a value of 'Error'. And I'm not aware of any way to set a 'Not Responding' for an accessory either thru a characteristic or the HAP event interface, except as a response to "GET /characteristics".
Creates a characteristic level status 'this.status' - Value …
=> Change updateValue to return not responding status

lib/Camera.js
This fixes the issue where you could not connect to multiple cameras at once when live.
SSRC should be a random 32 bit integer not always set to 1 for HomeKit to correctly be able to differentiate which stream is for which camera.
I have made it random on both audio and video streams, and have modified the ffmpeg call to correctly use this ssrc.
=> Changes SSRC to be random per prepareStream, not always 1

lib/Characteristic.js
JSON Dictionary objects are legacy supported with reads, but no writes (in iOS 11 at least).
The format key is ‘dict’, you will not be able to pair with the accessory if you define a characteristic with format ‘dictionary’.
Also there needs to be a default value of {} or the pairing will fail as well.
=> Legacy Dictionary Fixes

index.d.ts
The method was added in https://github.com/KhaosT/HAP-NodeJS/commit/c62294b3c5400157164a10a1e96a41259c3fc23b but was not added to the interface.
=> Add setupURI to the TypeScript def for Accessory

index.d.ts
I'm using this project is [one of my projects](https://github.com/JosephDuffy/homebridge-pc-volume) and found that the type that each of the services on `Service` have appears to be wrong.
Each predefined service property, e.g. [`Speaker`](https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/lib/gen/HomeKitTypes.js#L3365), is exposed as a `Service`, which has a constructor with the signature `(displayName: string, UUID: string, subtype: string): Service`, but I believe they actually have the signature `(displayName: string, subtype: string): Service`, because the UUID is predefined.
I have added a new type – `PredefinedService` – which has a constructor with the signature `(displayName: string, subtype: string): Service`, and updated the `index.d.ts` file.
=> Fix types of services exposed by Service

lib/Accessory.js
Throw an error when trying to add more than 99 bridged accessories to a bridge.
It's mostly relevant for homebridge, where a plugin doesn't know how many accessories have already been exposed by other plugins.  This seems the cleanest place to implement the check, though.
=> Check number of bridged accessories

lib/Accessory.js
In unpair handler I added extra check for _advertiser before we call update on it.
It fixes NRCHKB/node-red-contrib-homekit-bridged#22
In node-red-contrib-homekit-bridged we sometimes have situation like this:
- create bridge with accessory
- publish bridge
- add bridge in Home.app
- remove accessory from bridge and reload bridge
- bridge is not published due to no accessories
- remove bridge from Home.app cause fatal error (publish was not called so we have unassigned _advertiser)
=> During unpair make sure _advertiser is not null

lib/Accessory.js
=> Fix error message when adding >149 bridged accessories to a Bridge.

index.d.ts
Adding the following props to Service in index.d.ts:
```
isHiddenService: boolean;
isPrimaryService: boolean;
linkedServices: Service[];
```
@mzyy94 thoughts on these changes?
=> Add missing props of Service in Typescript

lib/Characteristic.js
Catch oldValue in setValue directly at the beginning to make sure cha…nge events are triggered as soon as value change.
Reason: I found some Homebridge Plugins that break the whole "sending change events" process by setting the value itself in the set-handler. The result is that old and new value are the the same and no change event is triggered at all.
Example: https://github.com/YinHangCode/homebridge-mi-aqara/blob/master/parser/GatewayParser.js#L267
This change would fix this and really compare oldValue from timepoint of the setValue call with the new value
@KhaosT
=>  catch oldValue in setValue directly at the beginning

src/lib/AccessoryLoader.ts
As mentioned in #701 typescript files would be ignored by the AccessoryLoader after the refactoring to typescript. Now AccessoryLoader will try to load javascript as well as typescript files.
=> Fixed: AccessoryLoader now loads typescript files correctly

src/lib/Accessory.ts, src/lib/HAPServer.ts
When HomeKit invokes a `/resource` request for a camera, which is not the primary accessory (for example for bridged cameras and maybe also multiple cameras in one bridge), HomeKit includes the `aid` property in the request to specify from which accessory the snapshot should be gathered. This property is currently ignored by HAP-NodeJS and as a result any sort of snapshot requests won't work for bridged cameras.
This PR fixes that issue.
=> Fixed: resource/snapshot requests for bridged cameras now work as intended

src/lib/StreamController.ts
When creating a new StreamController default values for the characteristics of the CameraRTPStreamManagment service are now correctly set.
After pairing with a newly created Camera/Video Doorbell accessory, for the first Discover call the value property for the characteristics of the CameraRTPStreamManagment service would be empty/non existent. HomeKit expects those values to be set.
=> Set default values when creating a CameraRTPStreamManagment service

src/lib/Accessory.ts, src/lib/HAPServer.ts, src/lib/model/AccessoryInfo.ts, src/lib/util/eventedhttp.ts, src/types.ts
**Reimplemented /pairings route to correctly match the HAP spec:**
- added permission management for paired controllers
- validate add/remove pairing request:
- check controller admin permission
- do not allow overriding of public key (add)
- add support for list pairings requests
- unpair every regular user controller when last admin controller unpairs
- destroy session if controller unpairs itself or any currently connected controller gets unpaired
<br>
Also in this PR:
- completed list of tlv values and status codes
- matched error response of pair-verify process to the expected behavior according to the HAP spec
<br>
<br>
Everything in this PR is tested and fulfills the expectations of the HAP spec :)
Happy to answer any questions concerning this PR
=> Reimplement /pairings route to match the HAP spec

src/lib/Accessory.ts, src/lib/HAPServer.ts
* Implement http response according to the spec:
* for writes:
* 204 "No Content" if no errors occurred
* 207 "Multi-Status" if at least one characteristic reports an error or returns a write response
* for reads:
* 200 if no errors occurred (also do not include the `status` property if `value` was returned successfully)
* 207 "Multi-Status" if at least one characteristic reports an error
* Added check to ensure operations performed on characteristics are actually permitted
=>  Implement /characteristics route according to the spec

src/Core.ts
Small change to allow overriding of the default type icon type which is displayed in the HomeKit pairing window. By default, accessories are published with the category type as "OTHER". This change will allow uses to override this type in their accessory code
=> Publishing accessory type icons for pairing

src/lib/Accessory.ts, src/lib/HAPServer.ts, src/lib/model/AccessoryInfo.ts, src/lib/util/eventedhttp.ts
Introduced with my PR in #702 the `sessions` variable in the Session class tracked all connected clients by the `username`. The `username` identifies every user connected to the home uniquely. As a result the `sessions` dictionary will get messed up with multiple Apple devices (from the same user/Apple ID) connecting and disconnecting from the HAP server.
Even though I knew that this id identifies every Apple ID connected to the home I messed that one up. Sorry for that. Here is the fix 😅
**Impact:**
To anyone who runs the current version and to clarify the impact. When you remove anybody from your home, the current HAP-NodeJS will have problems to kill any currently open connections from the user you are removing. Which means if devices from a persons in your home are currently connected …
=> Fixing session dictionary getting messed up handling multiple controllers of the same Apple ID

src/index.ts
Checking the content of the init function I assume the parameter should be an optional.
~ Andi
=> init function - optional parameter storagePath

src/accessories/AppleTVRemote_accessory.ts, src/lib/Accessory.ts, src/lib/Characteristic.ts, src/lib/HAPServer.ts, src/lib/HomeKitRemoteController.ts, src/lib/Service.ts, src/lib/gen/HomeKit-DataStream.ts, src/lib/gen/HomeKit-Remote.ts, src/lib/gen/index.ts, src/lib/util/tlv.ts
This PR adds support for Apple TV Remote accessories (though without support for Siri commands).
As this PR relies on the changes made in #702 those commits are also included here. So that PR needs to be merged first. But I didn't want to wait. Although #702 is still in review, discussion can already be started for this PR.
The main API for remotes is in `src/lib/HomeKitRemoteController.ts` (with all new characteristics in `src/lib/gen/HomeKit-Remote.ts`).
For demonstration purposes I created `src/accessories/AppleTVRemote_accessory.ts`, which exposes an http api (documented in the source file) in order to play around with it.
As noted in `src/lib/HomeKitRemoteController.ts` line 126 ff. persistent storage of the target configuration is still not implemented (as I'm not quite sure how to …
=> Apple TV remote

src/lib/Accessory.ts
Discovered new HomeKit accessory type, #33, which appears as a router image in the HomeKit pairing window. This change defines type 33 as "ROUTER"
=> HomeKit accessory types

src/lib/Accessory.ts, src/lib/Advertiser.ts, src/lib/HAPServer.ts, src/lib/util/eventedhttp.ts
This PR makes the following changes:
- The ProtocolInformation service gets added to the primary accessory
- The `/prepare` route got implemented to support prepared writes
<br>
Note:
I'm unsure what exactly the benefits are for prepared writes as no characteristics require it at this point. However I discovered that for lock services a HAP controller executes a prepared write when opening/closing. I don't know to which services this also applies.
=> Update to protocol version 1.1.0

src/lib/model/AccessoryInfo.spec.ts, src/lib/model/AccessoryInfo.ts
Added assert to check if supplied username matches the mac address pattern.
Additionally added test to verify that behavior.
=> Enforce usage of valid deviceId/username

src/lib/util/eventedhttp.ts
Fixes an issue introduced in #735 where after unpairing any controller any new connections to the same server will crash the server with this error:
```
/Users/samuel/Documents/Projects/hap-nodejs/dist/lib/util/eventedhttp.js:143
var sessions = _this._server.sessions[username];
^
TypeError: Cannot read property 'pairingid' of undefined
at Session.establishSession (/Users/samuel/Documents/Projects/hap-nodejs/dist/lib/util/eventedhttp.js:143:50)
at HAPServer._this._handlePairVerifyStepTwo (/Users/samuel/Documents/Projects/hap-nodejs/dist/lib/HAPServer.js:619:21)
at HAPServer._this._handlePairVerify (/Users/samuel/Documents/Projects/hap-nodejs/dist/lib/HAPServer.js:524:23)
at IncomingMessage.<anonymous> (/Users/samuel/Documents/Projects/hap-nodejs/dist/lib/HAPServer.js:252:39)
at …
```
=> Fix error connecting after unpairing

src/index.ts, src/lib/datastream/DataStreamManagement.ts, src/lib/datastream/DataStreamParser.ts, src/lib/datastream/DataStreamServer.ts, src/lib/datastream/index.ts, src/lib/util/encryption.ts, src/lib/util/eventedhttp.ts, src/lib/util/uuid.ts
This is part one of two PRs (Spoiler alter: part two will add support for Siri remotes. I'm finishing the last bits on that one).
This PR implements full support for HomeKit Data Streams.
The API is currently intended as follows:
* Step 1: You would create a new instance of the `DataStreamManagement` class and add the service returned by `getService()` to your accessory
* Step 2: finished
If an HomeKit Hub detects a combination of supported services it will create a connection.
You could then create some listeners for certain event messages with the respective protocol name (for example the `whoami` event message of the `targetControl` protocol. This is what the SiriRemote uses to identify DataStream sessions) or listen to more general events like `CONNECTION_OPENED` or …
=> Implemented the HomeKit Data Stream protocol

src/accessories/AppleTVRemote_accessory.ts, src/accessories/gstreamer-audioProducer.ts, src/index.ts, src/lib/Accessory.ts, src/lib/HomeKitRemoteController.ts, src/lib/datastream/DataStreamServer.ts
This part two of two (with part one being #736 and thus also containing the changes of the previous PR).
In this PR support for Siri voice input has been added. The provided example plugin was extended to show how supporting voice data is going to work (by default turned off). The only thing which you need to define is audio producer object, which generates individual opus frames (according to the supplied audio configuration) and calls the respective handler to send them out. I decided to include an example implementation which uses gstreamer and `alsasrc` (as most of the people run hap-nodejs on raspberry pis anyway. A implementation using `osxaudiosrc` would also be possible. However I couldn't get gstreamer to record any audio under macOS Catalina when executing gstreamer directly via …
=> Adding support for Siri remotes

src/lib/gen/importAsClasses.ts
Currently, building via `tsc` fails due to two missing type casts in `importAsClasses.ts` -> this doesn't affect running via `ts-node`, because the affected code is apparently not used anywhere else.
However, since the switch to TypeScript, building before running is quite advisable on embedded platforms (RPI et al.), since `ts-node` is incredibly slow there.
This pull requests adds the missing casts, so that `tsc` finishes without errors.
Also see #734
=> Add missing type cast to fix TypeScript build.

src/lib/Accessory.ts, src/lib/util/eventedhttp.ts
After calling unpublish the HTTP server will be stopped but all clients stay connected which you can see if you call netstat. Any data which will be sent from those connected clients will still be processed even though the bridge should not be published anymore at this point. The process must be killed to close those open connections.
This makes it impossible to unpublish and republish a bridge. Furthermore the publish method cannot be called again because the ProtocolInformation service will be added again. The application needs to be restarted in order to be able to publish the bridge again.
Those issues lead to the issue described under https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/12 where it is not possible to redeploy a bridge node in Node-RED by calling …
=> Fix unpublish function to close all open connections and allow republish

src/lib/datastream/DataStreamServer.ts
Messed this one up ... max payload length should be 1.048.575 bytes
Fixed now.
=> Fixed max payload length constant for data stream messages

src/lib/HAPServer.ts, src/lib/util/encryption.ts, src/lib/util/eventedhttp.ts
This PR ensures that the correct error codes are returned when a /pair-setup fails.
Additionally message authentication is now enforced for secured sessions.
=> Corrected returned error codes in /pair-setup and improved session security.

src/lib/HomeKitRemoteController.ts, src/lib/datastream/DataStreamServer.ts
Added missing enum for status codes used for HDS response messages.
The enum is taken from the homed binary.
=> Adding enum for HDS status codes

package-lock.json, package.json, src/accessories/gstreamer-audioProducer.ts, src/lib/Camera.ts, src/lib/datastream/DataStreamParser.ts, src/lib/util/hkdf.ts, src/lib/util/uuid.ts
This pull request implements the [proposed changes](https://github.com/KhaosT/HAP-NodeJS/issues/761#issuecomment-574480153) in issue #676 
1. Moves the Node engine support from v4 to v10 (48196df03a9f6d7c1d15614c457e7107d454621c).
2. Downgrades the Node `@types/node` from v12 to v10. This makes type type definitions match the major version and minor version tagged in the semver string of the Node's version (f07d4e98c34957021d46e3605759dcf977b42faf).
There are a few knock on effects from downgrading the `@types/node` from v12 to v10. Specifically, there were new build errors introduced (expand below for those errors fixed in f07d4e98c34957021d46e3605759dcf977b42faf).
<details><summary>Expand: Example build errors fixed by f07d4e98c34957021d46e3605759dcf977b42faf</summary>
<p>
```text
$ npm …
```
=> Resolve TypeScript Typings and Engine Version Conflict

package-lock.json, package.json, src/lib/Accessory.ts, src/lib/Characteristic.ts, src/lib/HAPServer.ts, src/lib/HomeKitRemoteController.ts, src/lib/StreamController.ts, src/lib/datastream/DataStreamManagement.ts, src/lib/datastream/DataStreamServer.ts, src/lib/model/AccessoryInfo.ts, src/lib/util/chacha20poly1305.ts, src/lib/util/encryption.ts, src/lib/util/eventedhttp.ts, src/lib/util/hkdf.ts, src/lib/util/tlv.ts, src/types/buffer-shims.d.ts
This PR removes the dependency of `buffer-shims` as node v4 support was dropped.
=> Remove obsolete dependency of buffer-shims

src/index.ts
As described in [homebridge#2391](https://github.com/nfarina/homebridge/pull/2391#issuecomment-575783120)
the old legacy types can now be imported in js like the following (instead of using direct file access like before).
```json
const legacyTypes = require('hap-nodejs').LegacyTypes;
```
=> Exporting legacy types

src/lib/Accessory.spec.ts, src/lib/Accessory.ts, src/lib/Characteristic.spec.ts, src/lib/Characteristic.ts, src/lib/Service.spec.ts, src/lib/Service.ts
Added for serialization and deserialization functions Accessory, Services and Characteristics to be used in homebridge as mentioned here in [homebridge/2391](https://github.com/nfarina/homebridge/pull/2391#issuecomment-575771704).
The goal is to improve maintainability and stability, so homebridge does not need to work on hap-nodejs internals.
Additionally the following things are now serialized correctly:
* Characteristic.accessRestrictedToAdmins
* Service.isHiddenService
* Service.isPrimaryService
* Service.optionalCharacteristics
=> Adding serialization and deserialization functions for Accessory, Services and Characteristics

.github/workflows/nodejs.yml, src/lib/Advertiser.spec.ts
This PR is a proposal to add a CI runner to the project.
There is no real benefit, if we have some unit tests but never run them and regressions potential get published unnoticed.
Additionally I fixed an already broken Tests in this PR.
I don't really care what CI runner we are going to use, I just picked Travis, since the integration with GitHub seems pretty good and it worked for me in the past.
Additionally you could hook up travis to [deploy npm releases](https://docs.travis-ci.com/user/deployment/npm/) (a new version is published for every tagged commit). For me this feature wasn't always reliable, but in every case you would need to finish the setup @KhaosT (setup travis for your account and maybe add deployment tokens).
=> Adding configuration for GitHub actions CI

src/lib/Service.ts, src/lib/gen/HomeKit-Bridge.ts, src/lib/gen/HomeKit-TV.ts
Mitigates regression introduced in https://github.com/KhaosT/HAP-NodeJS/pull/799 (and already discussed in https://github.com/KhaosT/HAP-NodeJS/pull/678).
See: https://github.com/KhaosT/HAP-NodeJS/blob/a3a49491c00e91ffb2a6dd4d3628e917cf61ddba/src/lib/Service.ts#L163-L165
For the long term I could imagine that we somehow alter the order in which required/optional characteristics get added and the display name gets translated into the Name characteristic.
=> Mitigating issues with required Name characteristic

src/lib/Accessory.ts
This basically move homebridges `getServiceByUUIDAndSubType` into hap-nodejs.
https://github.com/homebridge/homebridge/blob/e67630a3978aa126786711f8ec06610db517ca74/lib/platformAccessory.js#L113-L122
=> Adding getServiceById to retrieve Service by UUID and subtype

.github/workflows/nodejs.yml
Added a second job which automatically publishes the npm package.
It does only run if all previous build jobs were successful, the triggering event was `push` (so it doesn't run for pull_request or other future events) and the job got executed because a new version tag (a tag that starts with v; we cannot really use regex to match the version string exactly) was pushed.
For this to work you would need to add a secret called `npm_token` to the project (via settings) which contains a npm publish token.
Edit: You could also create a completely new workflow for publishing which only runs on the 'release' event. However you would then need to manually create a new release in GitHub to trigger this event. As this project didn't create a single GitHub release, I think checking for tags is …
=> Adding CD using GitHub Actions

src/accessories/AirConditioner_accessory.ts, src/lib/Accessory.ts, src/lib/HomeKitRemoteController.ts, src/lib/Service.ts
Simplified the setPrimaryService API call a bit.
`setPrimaryService` is now a member of the Service class (the old method in the Accessory class got deprecated and just forwards the call to this method). So now primary, hidden and linked service management is all at the same place. This enables homebridge plugin devs to set primary services (wasn't really possible before).
Removing primary services and adding them again could lead to multiple primary services. This is now taken care of correctly.
=> Improve setPrimaryService API a bit

src/accessories/Fan_accessory.ts, src/index.ts, src/lib/Characteristic.ts, src/lib/util/hapStatusError.ts
I didn't see the other PR until after I went to make this PR...
Usage (async is optional):
```ts
fan
.getService(Service.Fan)!
.addCharacteristic(Characteristic.RotationSpeed)
.onGet(async () => {
return FAKE_FAN.rSpeed;
})
.onSet(async (value) => {
FAKE_FAN.setSpeed(value);
});
```
The user can also throw a specific HAP error:
```ts
fan
.getService(Service.Fan)!
.addCharacteristic(Characteristic.RotationSpeed)
.onGet(async () => {
throw new HapStatusError(HAPStatus.OPERATION_TIMED_OUT);
});
```
If any other error types are thrown while executing the handler, it will fallback to `HAPStatus.SERVICE_COMMUNICATION_FAILURE`.
`HapStatusError` can also be used in the current style listeners:
```ts
fan
.getService(Service.Fan)!
.addCharacteristic(Characteristic.RotationSpeed)
.on('get', …
```
=> Add support for promise based Characteristic setters and getters

src/lib/Characteristic.ts, src/lib/HAPServer.ts, src/lib/util/hapStatusError.ts
The upper/lower bounds of the checks were reversed due to negative number confusion. I also refactored the duplicate checks into a single IsKnownHAPStatusError() function.
=> Fix incorrect bounds checks of HAPStatus errors

src/lib/util/request-util.spec.ts, src/lib/util/request-util.ts
Saw this with my temperature sensors that are used outdoor.
```
HAP-NodeJS:Accessory [Bart-Dev-1 C734] Got Characteristic "Current Temperature" value: "-2.299999999999997"
```
And after delving into the code found this issue with javascript math and negative or decimal values. This issue is only triggered when the minValue for a characteristic is a negative or decimal number.
Added 2 test cases to cover the identified scenarios
The fix is a bit of kludge versus adding in a proper math library.
=> Incorrect rounding breaking temperature values

package.json, src/lib/Accessory.ts, src/lib/Characteristic.spec.ts, src/lib/Characteristic.ts, src/lib/definitions/CharacteristicDefinitions.ts, src/lib/definitions/generator-configuration.ts, src/lib/util/hapStatusError.spec.ts, src/lib/util/request-util.ts
* Fix the `validateClientSuppliedValue` (renamed from `validClientSuppliedValue`)  method so it now transforms values to their corresponding types as expected (eg. transforms `false` to `0` for a UINT8 data type).
* Floats now have an upper and lower value defined so the validation methods used on INTs can largely be reused here.
* Check for non-finite numbers such as `Infinity` and `NaN` in client and user validation methods.
* When a `number` type is thrown or returned as a callback error, HAP will now verify it's a valid hap status number, or transform it into `HAPStatus.SERVICE_COMMUNICATION_FAILURE`.
* Added the `DEBUG_MESSAGE` level to `CharacteristicWarningType`
* Warnings about invalid write responses from a `SET` handler are now debug level characteristic warnings.
=> Fix Validate Client Supplied Values + float min/max

.eslintrc, package-lock.json, package.json, src/BridgedCore.ts, src/Core.ts, src/index.ts, src/lib/Accessory.ts, src/lib/Advertiser.ts, src/lib/HAPServer.ts, src/lib/model/AccessoryInfo.ts, src/lib/util/eventedhttp.ts, src/lib/util/setupcode.ts, src/lib/util/setupid.ts, src/scripts/generate-verifier.ts
Adds support for generating random setup codes if one isn't provided, and providing a salt+verifier instead of a setup code, and adds events for pair setup requests to present the setup code to the user. This also rejects pair setup requests if another client is pairing.
```ts
import {AccessoryEventTypes, Categories} from 'hap-nodejs';
const bridge = new Bridge('Node Bridge', uuid.generate('Node Bridge'));
bridge.publish({
username: 'CC:22:3D:E3:CE:30',
port: 51826,
category: Categories.BRIDGE,
});
bridge.on(AccessoryEventTypes.PAIR_SETUP_STARTED, (setupcode: string, setupuri: string, session: Session) => {
// Present the setup code to the user
// If we had some web interface here we could send a message to it to show the setup code and a QR code with the setup URI
// Or if we just want …
```
=> Support random setup codes and saved verifiers

package-lock.json
To receive multicast-dns update to 7.2.3 per https://github.com/homebridge/bonjour/issues/11
Signed-off-by: GitHub <noreply@github.com>
=> Bump bonjour-hap to 3.6.3

package-lock.json, package.json, src/lib/Accessory.spec.ts, src/lib/Accessory.ts, src/lib/Advertiser.ts, src/lib/util/promise-utils.ts
Currently the ability to republish (calling `Accessory.publish` after `unpublish` has been called) isn't really supported.
Further, there are regressions introduced in the past (see #895) which now prevent this completely.
This PR adds a minimal set of test cases to test the behavior of a `publish` call following a `unpublish` call.
With this test we identified three issues:
* The problem reported in #895 
* If `addIdentifyingMaterial` option was turned on, this was done a second time when republishing
* When `unpublish` is called instantly on the `LISTENING` event and the CIAO advertiser is used one might encounter a race condition where the Probing step isn't properly canceled (as the `unpublish` was called while the Networking stack was still initializing). This issue isn't currently …
=> Ensure Accessory is able to be republished

src/lib/util/hapCrypto.ts
As reported in #916, nodejs v17 ships with OpenSSL 3 on linux machines which require 96 bits nonce length for `chacha20-poly1305` (OpneSSL 1.x did automatically fill up with zeros).
_This is the PR for release 0.9.8 and is available as a beta release already._
This PR updates `hapCrypto` to automatically create a 96 bit buffer if necessary and fills it with zeros (as mandated by the HAP spec).
* Fixed an issue which crash on any client communication when running NodeJs 17 on linux based machines
Removed some leftover and unused typedef.
--
--
=> Fix hapCrypto crash for OpenSSL 3.x versions shipped with node v17 on linux

package-lock.json, package.json, src/lib/Accessory.ts, src/lib/Advertiser.ts, src/types/dbus-native.d.ts
HAP-NodeJS currently doesn't work on some set-ups ('No Response'!) due to some router bugs:
- Example: Arris G36 won't forward IPv4 multicast between wired and wireless interfaces. Bonjour-hap and Ciao advertisers won't advertise on IPv6. So you get no working advertisements if your HAP-NodeJS machine is connected via Ethernet instead of Wi-Fi.
HAP-NodeJS also currently doesn't work on other set-ups, for software-related reasons:
- Example: since on Linux Avahi is usually enabled by default, and HAP-NodeJS usually runs after Avahi, it cannot listen for unicast requests on 5353 even with SO_REUSEADDR. There are at least some routers which (even though they shouldn't) recreate multicast packets directed to a multicast group as unicast packets which are sent to connected devices joined to …
=> New advertiser: Avahi/D-Bus API

src/lib/Accessory.spec.ts, src/lib/Accessory.ts, src/lib/Advertiser.ts, src/types/dbus-native.d.ts
PR #918 introduced a new advertiser using native avahi over its dbus interface. The advertiser required to be manually enabled.
This PR adds additional heuristic to check if (a) dbus is installed and (b) avahi is installed. If both is the case hap-nodejs will use the `AVAHI` advertiser if nothing else is specified.
* The new `avahi` based advertiser will be automatically used on supported platforms.
Note, due to the fact that the new checks are performed asynchronously, the `Accessory.publish` signature was changed to return a `Promise<void>` instead of `void`.
Added an additional test case, ensuring that the availability check succeeds in CI environment.
--
=> Automatically use Avahi/DBus advertiser if available on platform

src/lib/Accessory.ts
For the beta period of 0.10.0 we changed how we select the default advertiser, moving from `bonjour` to `avahi` as a default if we our heuristic detects it being available on the platform.
This heuristic might not be perfect and might result in non advertised HAP service (see https://github.com/homebridge/homebridge/pull/3062#issuecomment-1014326006).
To avoid any breaking changes for existing users, this PR revers the default advertiser back to the `bonjour` package.
* Revert to `bonjour` as the default advertiser.
When selecting the `avahi` advertiser, this PR will now additionally run the availability check, and revert to `bonjour` if we find to be running on a non compatible platform. Additionally, we print an error message informing the user about it.
--
--
=> Use bonjour advertiser as default again, warn when Avahi is used on an unsupported platform.

src/lib/camera/RecordingManagement.ts, src/lib/datastream/DataStreamServer.ts
As reported in #926, shutting down `hap-nodejs` during an ongoing recording session will result in an unhandled erroneous state.
This PR introduces additional measures to gracefully exit a recording stream when encountering a closed socket!
Additionally, the "main loop" of the recording stream was refactored to ensure that resources are always freed once the stream has ended.
* Fixed an unhanded error when shutting down `hap-nodejs` while a HSV recording stream is still in progress.
* Improved handling of ongoing HSV recording streams to ensure resources are always freed in erroneous states.
This PR resolves #926.
Nothing changed.
--
=> HSV: Properly handle closed HDS connection; ensure recording streams are always freed

src/lib/Characteristic.ts, src/lib/HAPServer.ts, src/lib/util/once.ts
Noticed in homebridge/homebridge that using once() required the inner function to explicitly typed while returning any. So no type inference and more importantly potential bugs.
Easiest way to see the effect is on [TS playground](https://www.typescriptlang.org/play?ts=4.5.4#code/CYUwxgNghgTiAEAzArgOzAFwJYHtX2BwGUNlFEAKMKCCAIyjAGsAueCqN1ZAWzpBgBtALoBKeAF4AfPABuOLMFFt5igNwAoDSAAeABxwwMSNJlz48YEACEQiQyAA8AFXi6MIVMADO8AGKm2HhSFCjobM7K8FCoAJ7wAN4a8PAQIMbUtCDAkkg03iCayfBwpDD4FAB01bAA5t5saEyoOADuqCLi0onFKViI7JlpSj0pY-AYABYwbfCoIK3wAKIwMzAUAETOk1i+QwzMJuhB+JNQvjRwUMDx-J7wQ9nwdPHeODwgeAggEAVq8FgMjF4HgILcEI8cl8JlgPpUNqJNOMAL5uX4IJLjFKQ3IYGDIQq9MalZDlI5gKo1GD1RFE5HFZGaelaXQGIzkk4g9AgABybRcbh0Hi8vgCx3MITCYAiUVcmNS6QeNGGuUQ+UJxRJZIolMqdQa8CaLXanUkMnlfQGVGV2XEFrGUxmi3mixWa02212StoByYHPM8DOFwgVxuzxA9xxL3 …
=> Properly type once

src/lib/Characteristic.ts
The warning message for `props.maxValue` being below the minimum for the `format` is incorrectly using `numericUpperBound` instead of `numericLowerBound`. This only affects the warning message; The actual range check is applied correctly.
The equivalent code for `props.minValue` is correct.
Replace `numericUpperBound` by `numericLowerBound` when constructing the warning message.
Corrected warning message when an attempt is made to set `props.maxValue` to less than the minimum allowed value for the characteristic's type.
There do not appear to be any tests for the content of warning messages.
=> Corrected message for MaxValue<numericLowerBound (#937)

src/lib/datastream/DataStreamServer.ts
As reported in #931, we experienced a memory leak when continuously using HomeKit Secure Video.
We identified an issue in how we handle closing HomeKit DataStream connections. Every opened DataStream connection registers a `CLOSED` listener to its HAP connection, in order to ensure both connections are closed if the main HAP TCP socket dies. This listener was not removed properly when the HDS connection was closed through the remote host.
- Fixed a memory leak which occurred on every HDS closed by the remote host.
Added a debug message to monitor the listener count in the future.
--
CC @hjdhjd
=> Fixed memory leak with HomeKit DataStreams

src/lib/util/eventedhttp.ts, src/lib/util/net-utils.ts
https://github.com/nodejs/node/issues/42787
https://github.com/nodejs/node/pull/41431#discussion_r841277378
It's worth doing this sooner rather than later. There may be other compatibility issues in Node.js 18 we won't find until this one is patched.
The use of `@ts-expect-error` should alert us to remove the exception when @types/node is updated to 18 (if they decide to keep backwards compatibility with old versions, which they may not, be we need to).
Alternatively we could do something like this, but I feel like it will result in the exception never being removed in the future:
```ts
(info.family === "IPv6" || (info.family as unknown as string) === 6)
```
* Fix an issue with network interface family detection when running Node.js 18
Tests are still failing on Node v18.0.0 - out of …
=> Fix #945 - Node.js v18 os.networkInterfaces()[].family number/string comparison

src/lib/camera/RTPStreamManagement.ts, src/lib/util/eventedhttp.ts
As of some reports, it seems that there are still issues with memory leaks with listeners registered to `HAPConnection`.
This PR adds detailed debug information with the new `HAP-NodeJS:EventEmitter` for every registered and removed event listener on `HAPConnection` objects. This will help us to gather more detailed information about the situation.
* Added more detailed debugging for event listener registrations for `HAPConnection` objects.
The feature was verified locally.
CC: @hjdhjd
=> Introduce layer to debug event registrations on HAPConnection

src/lib/Accessory.ts
`[${this.displayName}]` was not being interpolated.
Use backtick formatting for the entire line.
=> Fix `[${this.displayName}]` interpolation for error displayed when Avahi is not available.

src/lib/Characteristic.spec.ts, src/lib/Characteristic.ts
Related:
- #955 
The provided fp value must be same with the characteristic value.
Previously, this didn't work because of remainder between provided value and minimum step size.
Therefore, I suggest a new stable constant, `epsilon`, which is 1.
This patch fixes the issue by reducing remainder significantly.
The value of the constant is `minimum`.
It would crash plugins if the value is under 1.
If your accessory have specific "level" of state, you can now change the ranges to 0~100%.
This makes your Siri reads the level of state properly.
No additional information needed
"should validate Formats.FLOAT with precision with minimum steps" have been added in `Characteristic.spec.ts#L1097`
You don't need hard mathematical understanding!
You can just test it with `eps = 0` or `eps = 1`.
=> Fix floating point validation on Characteristic Set

src/lib/util/eventedhttp.ts
Empirically proven that Apple backend processes multiple characteristics submitted in the same request in reverse order. In the current version, the characteristics array is populated in chronological order. In some situations, the incorrect order of characteristics can lead to the setting of an obsolete characteristic value.
For example, some Zigbee devices report the current state before the change which causes consequent updates within a very short time window. In this case, HAP-NodeJS sends multiple characteristics in the same request.
```
2022-08-26T21:04:30.554Z HAP-NodeJS:EventedHTTPServer:Connection [::ffff:10.10.10.139] HTTP request: /characteristics
2022-08-26T21:04:30.554Z HAP-NodeJS:HAPServer [0E:3B:79:C7:EE:E4] HAP Request: PUT /characteristics
2022-08-26T21:04:30.555Z …
```
=> Fix notification events order

src/lib/util/eventedhttp.ts
Currently, we set the `setNoDelay` tcp option for our internal http/tcp server, running for every connection.
This seemingly causes issues as identified in https://github.com/homebridge/homebridge/issues/3226#issuecomment-1246174713.
Particularly, according to the documentation, the property `response.connection` might be nulled once response.end() was called on it.
This PR removes this call, as `request.socket` and `response.connection` are the same object anyways.
* Fixed a potential crash occurring in some rare situations when handling http requests.
- Reported in https://github.com/homebridge/homebridge/issues/3226
--
--
=> Remove setNoDelay call to response socket

.github/release.yml, .github/workflows/pr-labeler.yml
Currently we rely on a GitHub action for release note generation. GitHub provides (for a while now) a release not generation toll out of the box.
This PR moves to the GitHub integrated release note generation tool.
We integrated the PR auto labeler as a separate GitHub Action.
* Added configuration for GitHub Release note generation.
--
--
=> Move to GitHub based release note generation

src/lib/Characteristic.spec.ts, src/lib/Characteristic.ts
The release of v0.10.3 introduced fixes to the float rounding mechanism (see #956, #958). It introduced a regression when no `minValue` was provided (see #971).
This PR introduces a fix for this regression.
* Fixed a regression where floats were rounded incorrectly when no `minValue` was provided
This regression slipped through in this review step: https://github.com/homebridge/HAP-NodeJS/pull/958/files#r893353790.
A regression test was added, covering this case.
--
=> Fixed a regression where floats were rounded incorrectly when no minValue was provided

src/lib/Characteristic.ts, src/lib/Service.ts, src/lib/definitions/CharacteristicDefinitions.spec.ts, src/lib/definitions/CharacteristicDefinitions.ts, src/lib/definitions/ServiceDefinitions.spec.ts, src/lib/definitions/ServiceDefinitions.ts, src/lib/definitions/generate-definitions.ts
Current service and characteristic definitions reflect the state of iOS 15.
This PR regenerates service and characteristic definitions with the latest changes of iOS 16.
- Added `FirmwareUpdate` service definition
- Added `TapManagement` service definition
- Updated `AccessoryMetrics` service definition
- Updated `PowerManagement` service definition
This PR fixes a small issue in the definition generator script.
Tests were generated accordingly.
--
=> Update service and characteristic definitions to iOS 16

src/lib/Characteristic.spec.ts, src/lib/Characteristic.ts, src/types.ts
Value correction was introduced in #902. The PR didn't introduce any test cases and also didn't handle a lot of edge cases (see https://github.com/homebridge/HAP-NodeJS/pull/902#issuecomment-1278578336).
This PR iterates on this changes by:
- Adding test coverage
- Skipping value correction in certain edge cases.
--
Tests were added to verify that setProps corrects numeric and string based formats if bounds restrictions change.
Tests were added to ensure that there aren't any faulty CHANGE events generated.
--
CC: @ebaauw
=> Iterate on characteristic value correction when calling setProps

src/lib/camera/RecordingManagement.ts
As described in #976, the `DOORBELL` event trigger is part of HomeKit specification (as discovery through reversing certified accessories) but isn't implemented by Apples HomeKit client-side.
This PR clarifies this matter in the documentation of the `EventTriggerOption` definitions.
- Clarified technical documentation of `EventTriggerOption.DOORBELL`.
--
--
=> Document that `DOORBELL` EventTriggerOption is not supported by HomeKit client side

src/lib/Accessory.ts, src/lib/Advertiser.ts
Homebridge currently supports [three different mDNS advertisers][mdns], two that run in-process and one that uses Avahi over D-Bus. For a while now, systemd-resolved has supported acting as an mDNS advertiser and resolver. If Homebridge is run on a system that uses systemd-resolved for mDNS, this can cause conflicts similar to homebridge/homebridge#3077.
systemd-resolved, like Avahi, exposes [a D-Bus interface][dbus] for managing mDNS services. This pull request adds a systemd-resolved mDNS advertiser that makes use of this interface. The code was heavily based on that of the Avahi advertiser.
- Added a new mDNS advertiser named `resolved` that uses systemd-resolved via D-Bus.
In order for homebridge to have the permission to use this interface, a `.pkla` file with the following contents …
=> Add systemd-resolved mDNS advertiser support

src/lib/Accessory.ts, src/lib/Advertiser.ts, src/types/dbus-native.d.ts
As of now we don't detect restarts of Avahi Deamon and therefore remain without an advertising in this situation as explained in #923.
This PR fixes this by subscribing on the dbus `StateChanged` listener to detect avahi deamon restarts.
* Properly recreate advertisements on restarts of avahi when using the avahi/dbus based advertiser.
--
--
=> Register listener on the dbus interface to detect Avahi deamon restarts

src/lib/Characteristic.ts, src/lib/Service.ts
Currently, `updateCharacteristic ` and `setCharacteristic` (`Service` class) don't expose the same method signature as `updateValue` and `setValue` (`Characteristic` class) methods. This was reported in #974.
This PR adapts the method signatures and adds proper documentation.
- Ensure that `updateCharacteristic ` and `setCharacteristic` (`Service` class) method signatures are in sync with `updateValue` and `setValue` (`Characteristic` class) methods.
This PR fixes some spelling mistakes.
--
--
=> Ensure updateCharacteristic and setCharacteristic method signatures are in sync with updateValue and setValue.

package-lock.json, package.json, src/lib/Advertiser.ts, src/types/dbus-native.d.ts
Per #980, the systemd-resolved advertiser reports that it's available even if systemd-resolved has mDNS disabled.
Check that mDNS is enabled in systemd-resolved before reporting that it is available as an advertiser.
--
--
--
This also adds a note to the error message when advertisements fail that there may be a permissions issue and the user should check the wiki for more details. The info to be added to the wiki will be posted in #980.
=> Ensure systemd-resolved has mDNS enabled

src/lib/Accessory.ts, src/types.ts
#973 retyped the `Accessory.addService(...)` method to provide more clear typing when supplying a service using its constructor. This method used, my accident, a type which was internal to the jest testing framework.
This PR packages the type as part of `hap-nodejs` itself.
* Fixed an issue where `addService` referenced an internal type of the jest testing library.
--
--
=> Remove accidental usage of private jest type

package-lock.json, package.json, src/accessories/Camera_accessory.ts, src/accessories/gstreamer-audioProducer.ts, src/lib/datastream/DataStreamParser.ts, src/lib/util/eventedhttp.spec.ts, src/lib/util/eventedhttp.ts, src/lib/util/hapCrypto.ts, src/lib/util/net-utils.ts
We currently still use node v10 as the minimum requirement. node v10 went out of LTS state long time ago. Further, we are several versions behind for jest and eslint.
This PR:
* Upgrades drops support for any node version prior to v14 (being the current LTS, see [releases](https://nodejs.dev/en/about/releases/))
* Upgrade dependencies
* Upgrade developer dependencies
* Update code to the updated typings.
* This releases drops support for node v10 and v12, making node v14 the minimum supported version.
--
--
=> Upgrade minimum node version and dependency maintenance

README.md
Currently, the README doesn't specify the date of Apples DCMA request, see #986.
This PR addresses this issue by including the date.
--
--
--
=> Add year to DCMA note in README

src/lib/Advertiser.ts, src/types/dbus-native.d.ts
Currently using hap-nodejs/homebridge as a dependency is a struggle in strongly typed environments as reported in #998.
This PR refactors the exported interface of HAP-NodeJS such that the internal type declaration file is not part of it anymore.
* Fixes an issue compiling projects relying on hap-nodejs that enforce strict type rules.
--
--
=> Refactor DBus InvokeError
