AccessoryController.js, Characteristic.js, Server.js, accessories/GarageDoorOpener_accessory.js
Temporarily reverts KhaosT/HAP-NodeJS#82 as it breaks bridged accessories...
=> Revert "Async Characteristic Reads"

accessories/types.js
Service and Characteristic defines (as used by iOS9b2) for new Security Alarm and Window Covering support.
=> Added some additional iOS9 characterstic and service constants

Accessory.js, Advertiser.js, accessories/types.js
- Category Types
- Extend Advertiser and Accessory to (optionally) provide a transport type
=> Added support for iOS9 Transport Category

accessories/types.js
for use with homebridge and the upcoming FHEM platform shim http://forum.fhem.de/index.php/topic,32652.msg314166.html#msg314166
Also more sensor = more fun ;)
=> Added humidity, temperature stypes

lib/AccessoryLoader.js
- Monkey-patches the `updateValue()` function into Characteristic
objects passed via `onRegister()`.
=> Support updateValue for imported Accessories

accessories/Lock_accessory.js, accessories/TemperatureSensor_accessory.js, lib/Accessory.js, lib/Service.js, lib/gen/HomeKitTypes.js, lib/gen/import.js
- Allow constructor references in both get and add for
Service/Characteristic
=> Allow for consistent service/characteristic syntax

accessories/Light_accessory.js, accessories/Lock_accessory.js, lib/Accessory.js, lib/AccessoryLoader.js, lib/Service.js, lib/gen/HomeKitTypes.js, lib/gen/import.js
- Convert sample Light accessory to new API
=> Support Service display names

lib/AccessoryLoader.js, lib/Characteristic.js, lib/gen/HomeKitTypes.js, lib/gen/import.js
- Use new Characteristic "props" to store things like minValue, etc.
- New chainable method Characteristic.setProps()
- Fix for 'int' characteristic formats
=> Simplify Characteristic properties

lib/Characteristic.js
This feature is not actually supported by the HAP protocol.
=> Don't permit changing value in setValue event

lib/Accessory.js, lib/Advertiser.js, lib/Characteristic.js, lib/HAPServer.js, lib/gen/HomeKitTypes.js, package.json
Added the support for dynamically add/remove bridged accessory.
Added the support for update bridged accessory's reachability.
=> Bridge Update

package.json
all source files should include the apache license copyright with appropriate owner and date.
=> Update license to Apache License 2.0

accessories/Fan_accessory.js, accessories/GarageDoorOpener_accessory.js, accessories/Outlet_accessory.js
Updated some of the accessory files to the latest spec. Also included an Outlet_accessory.js which can be used by others.
=> Updated Accessory Files

lib/camera/RTPProxy.js
See https://github.com/luisiam/homebridge-foscamcamera/issues/3
=> Fix crash when improper RTP and/or RTCP packets are received by the RTP Proxy

lib/HAPServer.js, lib/StreamController.js, lib/model/AccessoryInfo.js, lib/util/chacha20poly1305.js, lib/util/encryption.js, lib/util/eventedhttp.js, lib/util/hkdf.js, lib/util/tlv.js, package.json
Replace all Buffer.alloc and Buffer.from calls with buffer-shims
Also "npm install" has corrected the order of dependencies
My editor (Atom) has automatically removed indentation on empty lines too
I have tested on node4 and node6 and it solves the issue (#322)
=> Use bufferShim for node 4 support

README.md
adds a list of projects based on HAP-NodeJS
=> some Advertising ;-)

lib/util/encryption.js
Completes the move from curve25519-n to curve25519-n2
=> Update code dependency to use curve25519-n2

README.md
=> Readme (#389)

lib/Accessory.js, lib/model/AccessoryInfo.js, lib/model/IdentifierCache.js
Hi,
I want to propose this solution to remove all belongings of an accessory which is being destroyed.
Thank you!
=> remove persisted files when accessory is destroyed

lib/Accessory.js
=> Adding default version number to new accessory.

lib/Characteristic.js
* Fixed bug where Siri gives true/false in place of 1/0
=> Fixed bug with strange value from Siri

lib/Accessory.js
=> Unsubscribed events are deleted and not false

accessories/TV_accessory.js, lib/Accessory.js, lib/Characteristic.js, lib/gen/HomeKitTypes-Television.js, lib/gen/HomeKitTypes.js
Add basic TV support based on implementation in iOS 12.2 beta 1.
=> Basic TV support

lib/Accessory.js, lib/HAPServer.js, lib/model/AccessoryInfo.js, lib/util/encryption.js, package.json
Use TweetNaCl instead of libsodium.js
=> Switch to TweetNaCl

index.d.ts
It has wrong type that I previously pull-requested #669. And missing Service prototypes are added.
=> Fix and improve typescript definition

README.md
I just changed the README to represent the newest Node-RED repo, which is still updated/developed, so if someone finds it here, can use the latest one.
=> Changed Node-RED repo to the newest one

README.md, src/index.ts
This is a follow-up PR for any issues/breakages introduced by #691
=> Fix minor breakages in v0.5

src/lib/Characteristic.spec.ts, src/lib/Characteristic.ts
This PR fixes a regression introduced in bb0c5b9af02e.
Issue discussed in #721.
=> Fixed: floating point values are now validated correctly again

src/lib/Characteristic.ts, src/lib/gen/HomeKit.ts
* Fixed 'ManuallyDisabled' characteristic definition
* Added missing 'CameraOperatingModeIndicator' characteristic (optional) to the CameraOperationMode service
=> Corrected some minor issues regarding the CameraOperationMode service

src/accessories/AirConditioner_accessory.ts, src/accessories/Fan_accessory.ts, src/accessories/GarageDoorOpener_accessory.ts, src/accessories/Light_accessory.ts, src/accessories/Lock_accessory.ts, src/accessories/MotionSensor_accessory.ts, src/accessories/Outlet_accessory.ts, src/accessories/Sprinkler_accessory.ts, src/accessories/TV_accessory.ts, src/accessories/TemperatureSensor_accessory.ts, src/accessories/Thermostat_accessory.ts
Does not seem to work on the Thermostat for some reason, but works on all others.
=> Add categories to accessories

src/lib/util/eventedhttp.ts
=> Encryption order is now ensured when queueing event data.

README.md
=> Delete Old NPM Badge

src/accessories/SmartSpeaker_accessory.ts, src/lib/Accessory.ts, src/lib/Characteristic.ts, src/lib/Service.ts, src/lib/gen/HomeKit-TV.ts, src/lib/gen/HomeKit.ts
This PR updates some services to the most recent definition.
Newly added services:
* SmartSpeaker (originally https://github.com/KhaosT/HAP-NodeJS/pull/798)
* PowerManagement
* TransferTransportManagement
Edit: Additionally added the service AccessControl (is already in the spec like at least last year)
=> Updated services and characteristics to reflect the latest specification of iOS 13.4

src/lib/Characteristic.ts, src/lib/Service.ts
* Adding ability to replace characteristics of a service with the characteristics of another service (of the same service type)
* Fixed some typings
=> Adding ability to replace characteristics of a service with the characteristics of another service (of the same service type)

src/lib/Accessory.ts
aid and iid are swapped in debug message
=> Fixed `Could not find a Characteristic` debug message

src/accessories/gstreamer-audioProducer.ts, src/lib/Accessory.ts, src/lib/Characteristic.ts, src/lib/HAPServer.ts, src/lib/Service.ts, src/lib/controller/RemoteController.ts, src/lib/datastream/DataStreamParser.ts, src/lib/definitions/generate-definitions.ts, src/lib/model/AccessoryInfo.ts, src/lib/util/clone.ts, src/lib/util/eventedhttp.ts, src/lib/util/uuid.ts
for...in will iterate inherited enumerable properties.  Other nodes added properties to Array and were being iterated as well causing strange errors.
The following refactors were applied:
- for...in was changed to for...of.  In places where Typescript complains, a guard was added.
- added a radix of 10 to all parseInt calls
- removed unnecessary escape characters in regular expression strings
- removed unnecessary semicolons in class function declaration
- changed Typescript namespace to ES2015 class
=> Refactor for...in to for...of

package-lock.json, package.json, src/lib/Accessory.ts, src/lib/Characteristic.spec.ts, src/lib/Characteristic.ts, src/lib/Service.ts, src/lib/controller/CameraController.ts, src/lib/definitions/CharacteristicDefinitions.ts, src/lib/definitions/generator-configuration.ts
Throw more warnings instead of errors, if invalid value is supplied, revert back to last known good value, or a default.
=> Update validateUserInput to fix invalid values in more scenarios

src/lib/util/eventedhttp.ts
Currently, event notifications are queued based on their event name (aid and iid identifiers) and events with immediate delivery can bypass the queuing process.
This might yield the following problems:
* A event with a obsolete value might never reach the event receivers (e.g. switch flipping to off and on again might only yield the event notification for on)
* The order of delivery is not guaranteed with characteristics which are delivered instantly.
This PR reworks the event notification queuing as follows
* Replaced the event name indexed queue by a simple array based queue. Events are only filtered if they are **identical**.
* When we receive a characteristic event with immediate delivery we will flush the whole queue. This will possibly reduce the amount of event notifications and …
=> Rework event notification queuing
